name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./cmd/api

    - name: Build the Go binary
      run: GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
      working-directory: ./cmd/api

    - name: Zip the binary
      run: zip function.zip bootstrap
      working-directory: ./cmd/api

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: aws lambda update-function-code --function-name go-lambda-cicd --zip-file fileb://function.zip
      working-directory: ./cmd/api
